apiVersion: v1
kind: ConfigMap
metadata:
  name: before-api-config
  namespace: flask-apps
data:
  .env: |
    SUPABASE_URL:https://ekybmuyqummcaqfpkzrt.supabase.co
    SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreWJtdXlxdW1tY2FxZnBrenJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTAwNjAsImV4cCI6MjA4ODM4NjA2MH0.cLrcOD3jIoT-ngLyX9fayQhm5rZXAmjZ-yrEze4Xl2E
    SUPABASE_TABLE:fire_readings
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: during-api-config
  namespace: flask-apps
data:
  .env: |
    SUPABASE_URL= https://ekybmuyqummcaqfpkzrt.supabase.co
    SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreWJtdXlxdW1tY2FxZnBrenJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTAwNjAsImV4cCI6MjA4ODM4NjA2MH0.cLrcOD3jIoT-ngLyX9fayQhm5rZXAmjZ-yrEze4Xl2E
    SUPABASE_EDGE_URL=https://ekybmuyqummcaqfpkzrt.supabase.co/functions/v1/ai-detection
    FLASK_PORT=5000
    MODEL_WEIGHTS=./models/best.pt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: after-api-config
  namespace: flask-apps
data:
  .env: |
    NASA_FIRMS_KEY :49f9394f76de0cd3260ce5ae923a4832
    SUPABASE_URL:https://ekybmuyqummcaqfpkzrt.supabase.co
    SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreWJtdXlxdW1tY2FxZnBrenJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTAwNjAsImV4cCI6MjA4ODM4NjA2MH0.cLrcOD3jIoT-ngLyX9fayQhm5rZXAmjZ-yrEze4Xl2E
    GEMINI_API_KEY:AIzaSyB9oL2xIzgbOijP1BGL-jlvRjbeCAgk8Ps
    SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreWJtdXlxdW1tY2FxZnBrenJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTAwNjAsImV4cCI6MjA4ODM4NjA2MH0.cLrcOD3jIoT-ngLyX9fayQhm5rZXAmjZ-yrEze4Xl2E   # for reading back data
    REPORT_EVERY_N_DAYS:7           
    EMERGENCY_FIRE_THRESHOLD:15    