[supervisord]
nodaemon=true
user=root

[program:flask-app]
command=python3 app.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:additional-script]
command=python3 simulator.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0